### ISSUE TITLE
There is no official MineClone 2 issue tracker.

### ISSUE THREAD

**Issue by anon55555** [kay27/MineClone2#5]
Should I just use this as a MineClone 2 issue tracker?

**Comment by kay27** [comment]
Sure, I'll do what I can... Slime blocks are just unfamiliar for me :) I started to gather the information: how to reproduce, how it must be...

But this is mine, not @Wuzzy2 's fork, so I'm not sure, he said to post issues to MCL2 forum topic, probably better to do that.

Forum isn't a tracker, but @Wuzzy2 also has own GitHub repo with only the tracker :) I'll follow his decision and l can't ignore the issues published here, so for myself it is all okay.

**Comment by kay27** [comment]
Closed accidentally :) Reopened. Won't close for now, maybe somebody else will comment.

**Comment by anon55555** [comment]
https://github.com/Wuzzy2/MineClone2-Bugs is archived, new issues can't be opened.

**Comment by Wuzzy2** [comment]
https://git.minetest.land/Wuzzy/MineClone2 is back in town!

Now if only I knew how to backup issues from Gitea …

**Comment by anon55555** [comment]
> https://git.minetest.land/Wuzzy/MineClone2 is back in town!
> 
> Now if only I knew how to backup issues from Gitea …

```sh
for i in $(seq 837) # put latest issue number instead of 837
do
	wget https://git.minetest.land/Wuzzy/MineClone2/issues/$i
done
```

**Comment by Wuzzy2** [comment]
Very funny …

**Comment by kay27** [comment]
> ```shell
> for i in $(seq 837) # put latest issue number instead of 837
> do
> 	wget https://git.minetest.land/Wuzzy/MineClone2/issues/$i
> done
> ```

Nice! I experimented with ```wget -erobots=off --recursive https://git.minetest.land/Wuzzy/MineClone2/``` but it wasn't a good way really. Now saved it under Windows by ```for /l %a in (1,1,900) do wget https://git.minetest.land/Wuzzy/MineClone2/issues/%a --output-document=%a.html```

**Comment by anon55555** [comment]
I've come up with this to back up the MineClone2 repo + issues:
```sh
# clone all branches on the repo

git clone --mirror https://git.minetest.land/Wuzzy/MineClone2

# download issues

mkdir -p issues

for i in $(seq 837) # put latest issue number instead of 837
do
	curl https://git.minetest.land/Wuzzy/MineClone2/issues/$i >issues/$i.html
done

# download attachments

uuidre='[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

mkdir -p attachments

for attachment in $(grep -Eoh "attachments/$uuidre" issues/*.html | sort | uniq)
do
	curl https://git.minetest.land/$attachment >$attachment
done
```
