### ISSUE TITLE
Ender Dragons.

### ISSUE THREAD

**Issue by dragonfly-ai** [kay27/MineClone2#7]
Assuming the goal of recreating minecraft behavior, a first encounter with the end seems to have uncovered some bugs:

On our first attempt to fight the Ender Dragon, our party located a stronghold, filled in the Eyes of Ender, and teleported to the End.  According to server logs, we arrived at roughly: 04:37:09

Bug 1:  At 04:37:39, an error message appeared in the logs:
`WARNING[Emerge-0]: Ender dragon doesn't want to spawn at (0,-26992,0)`
This message kept repeating for about 3 minutes, until 04:40:05.

Bug 2: Then, for a brief moment, the Ender Dragon appeared, then suddenly disappeared again.

Bug 3: None of the Endermen, unless attacked,  or Shulker Boxes engaged the players in combat. 

Bug 3.5: No end crystals appeared.

Bug 4:  When entities or players go through Nether portals, the logs announce the event, should a similar announcement accompany end portal use?

Bug 5:  Unable to re-open the portal, I tried to re-generate it with chat console invocations of: /deletebocks.  These could remove the end gateway, end obsidian entry platform, and the stronghold, but while the map generator regenerated the terrain, it left out these structures.  Is that normal?  (Note: Calling minetest.delete_area(pos1, pos2) from a custom mod seems to have the desired effect of regenerating the structures.)

Bug 6:  After deleting the entire stronghold with: /deleteblocks, thrown Eyes of Ender still homed in on where the stronghold had been.

Bug 7:  After writing and invoking a mod to force a call to minetest.delete_area(pos1, pos2) on both the stronghold and the end, Bug 1 returned.  This time, the dragon appeared frozen, high in the sky above the end gateway which appeared with the portal already activated.  It continued launching purple fire charge attacks, but didn't animate its wings or move at all.

Bug 8:  The end gateway seems to have generated in an already open state, regardless of whether dragon combat occurred. 

Bug 9:  Unable to fight the frozen out of reach dragon (in this test, I had no ranged weapons), I jumped through the end gateway portal without engaging the dragon at all.  Credits rolled, and the player re-appears at last spawn point, but the dragon seems to be gone forever anyway.

Details: 
Server runs Minetest 5.6.0-dev on debian 11.2.  Clients running Ubuntu, Rasbpian, and Windows.
Mineclone version: Version: 0.71.7 Release Candidate 0.

**Comment by kay27** [comment]
Very sorry, I haven't time to update this repo.
I'll do, just don't know when.
Main repo is: https://git.minetest.land/MineClone5/MineClone5
Fresh MineClone 5.1.5 is also available through Minetest Condent DB

**Comment by dragonfly-ai** [comment]
My mistake!  Thank you for the response and updates!  :)
